- name: Set up new Apple MacBook.
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Configure MacOS defaults in System Settings.
      ansible.builtin.script:
        cmd: macos-defaults.sh
        executable: /bin/zsh

    - name: Disable zsh last login prompt.
      ansible.builtin.file:
        state: touch
        mode: '0644'
        path: "{{ ansible_env.HOME }}/.hushlogin"

    - name: Install packages with Homebrew
      community.general.homebrew:
        pkg: 
