# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

## zsh

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git github zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# Environment variables

export EDITOR=nvim

## Aliases

alias ..="cd .."
alias cp="cp -i"
alias downloads="~/Downloads"
alias mv="mv -i"
alias rm="rm -i"

# Packages

export PATH=$PATH:/snap/bin

## Langauges

export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export PATH=/usr/local/texlive/2022/bin/x86_64-linux:$PATH
[ -f "/home/sean/.ghcup/env" ] && source "/home/sean/.ghcup/env" # ghcup-env

## Tools

export PATH=$PATH:$HOME/.pub-cache/bin
export PATH="/home/sean/.deta/bin:$PATH"
export FLYCTL_INSTALL="/home/sean/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

## Powerlevel10k

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
